spring:
  datasource:
    url: jdbc:tc:postgresql:15.5:///payment_api_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  flyway:
    enabled: false

  test:
    database:
      replace: none

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    '[com.paymentapi]': ${LOG_LEVEL:INFO}
    '[org.testcontainers]': INFO
    '[com.github.dockerjava]': WARN
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always