spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:50}
      minimum-idle: ${DB_POOL_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:60000}
  jpa:
    show-sql: false
    properties:
      hibernate:
        '[format_sql]': false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

logging:
  level:
    '[com.paymentapi]': INFO
    '[org.springframework.security]': WARN
    '[org.hibernate.SQL]': WARN
  file:
    name: ${LOG_FILE_PATH:/var/log/payment-api/payment-api.log}

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus