server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: payment-api
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_api
    username: ${DB_USERNAME:payment_user}
    password: ${DB_PASSWORD:payment_pass}

    hikari:
      pool-name: PaymentApiHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    validate-on-migrate: true
    out-of-order: false

logging:
  level:
    # Nível de log pode ser sobrescrito pela variável de ambiente LOG_LEVEL
    root: ${LOG_LEVEL:INFO}
    '[com.paymentapi]': ${LOG_LEVEL:INFO}
    '[org.springframework.web]': WARN
    '[org.springframework.security]': WARN
    '[org.hibernate]': WARN
  # Obs: O formato dos logs é controlado pelo logback-spring.xml

  request-response:
    enabled: true
    include-headers: false
    include-query-params: true

# Configurações do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html